// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Backtop: typeof import('./src/components/backtop/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Pane: typeof import('./src/components/splitpane/pane.vue')['default']
    Resizer: typeof import('./src/components/splitpane/resizer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splitpane: typeof import('./src/components/splitpane/index.vue')['default']
  }
}
